@startuml

class Dim3d<T>{
    +T x;
    +T y;
    +T z;
}

class Grid3d {
+Dim3d<size_t> dimensions
#field2
~method1()
+method2()
~method3()
+method4()
}

class GridBlock3d {
    +size_t idxStart{}        
    +Dim3d<size_t> dimensions
}



Grid3d *-- GridBlock3d
Grid3d *-- Dim3d

GridBlock3d *-- Dim3d

@enduml